Update the default cluster location
appbaseio/dashboard pull request #480
Opened 2022-04-11 11:50 UTC by lohi212

## What is this PR for?

https://www.notion.so/appbase/Update-the-default-cluster-location-6f16e1a1525e42bfa3d18f81a2a42047

## How have you tested this PR?

Loom: Will add it.

## What pages does it affect

2022-04-13 06:27 UTC, siddharthlatest commented
@lohi212 Remove the decimal from the ping time: https://i.imgur.com/ZM475xV.png. The value should be a whole number.

2022-04-20 06:18 UTC, lohi212 commented
https://www.loom.com/share/9534f70841964c00b32e20f9ca3fa366

2022-04-28 23:35 UTC, siddharthlatest commented on src/pages/ClusterPage/new.js
> +						{this.state.region}) is: {pingTime}ms
```suggestion
						{this.state.region}) from your location is: {pingTime}ms
```

2022-04-28 23:36 UTC, siddharthlatest commented on src/pages/ClusterPage/NewMyCluster.js
> +						{this.state.region}) is: {pingTime}ms
```suggestion
						{this.state.region}) from your location is: {pingTime}ms
```

2022-04-28 23:36 UTC, siddharthlatest approved these changes

2022-05-07 18:29 UTC, siddharthlatest requested changes
**Issue**:

- [ ] There should be a live value that is displayed as the API calls are made before the pulse. The pulse animation is to indicate that the value isn't final yet. Currently, no time is being shown.

![](https://i.imgur.com/DKCPSl6.png)

2022-05-11 19:25 UTC, merged